#!/usr/bin/env php
<?php

if(php_sapi_name() !== 'cli') exit;

require __DIR__.'/vendor/autoload.php';

use Martijnvdb\PhpCli\Cli;
use Martijnvdb\PhpCli\Command;
use Martijnvdb\PhpCli\Input\Text;

$cli = new Cli('First CLI App', '');

$cli->addCommand(
    Command::default()
        ->addOption('help', 'The name that should be printed.', 'h')
        ->addAction(function($input, $output) {
            $output->currentLine("HELP", 'blue');
        })
)
->addCommand(
    Command::new('test')
        ->addOption('name', 'The name that should be printed.', 'n')
        ->addAction(function($input, $output) {
            $output->currentLine($input->name, 'red');
            $output->newLine($input->name, 'blue');
        })
)
->addCommand(
    Command::new('test:input')
        ->addAction(function($input, $output, $command) {
            $name = Text::new('What is your name?', ['black', 'bg:white']);
            $age = Text::new('What is your age?', 'green', 'blue');

            $command->setInput('name', $name);
            $command->setInput('age', $age);
        })
);

$cli->run();