#!/usr/bin/env php
<?php

if(php_sapi_name() !== 'cli') exit;

require __DIR__.'/vendor/autoload.php';

use Martijnvdb\PhpCli\Cli;
use Martijnvdb\PhpCli\Input;

$cli = new Cli('First CLI App', '');

$cli->add(function($input, $output) {
    if($input->get('-h', '--help')) {
        $output->line('HELP');
    }

    if($input->get('-v', '--version')) {
        $output->line('VERSION');
    }

})->add('test', function($input, $output) {
    $name = $input->get('-n', '--name');

    $name = !empty($name) ? $name : Input::text('[yellow]What is your name?[/yellow]')->run();

    $output->line("Lorem ipsum [bold][red]{$name}[/red][/bold] amet, consectetur adipiscing elit.");
    
})->run();